CREATE DATABASE IF NOT EXISTS flow CHARACTER SET utf8 COLLATE utf8_general_ci;
CREATE DATABASE IF NOT EXISTS flow_upgrade CHARACTER SET utf8 COLLATE utf8_general_ci;

CREATE USER IF NOT EXISTS 'flow'@'%' IDENTIFIED WITH mysql_native_password BY 'flow';
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, INDEX, DROP, ALTER, CREATE TEMPORARY TABLES, LOCK TABLES ON flow.* TO 'flow'@'%';
GRANT ALL PRIVILEGES ON flow.* TO 'flow'@'%';
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, INDEX, DROP, ALTER, CREATE TEMPORARY TABLES, LOCK TABLES ON flow_upgrade.* TO 'flow'@'%';
GRANT ALL PRIVILEGES ON flow_upgrade.* TO 'flow'@'%';
FLUSH PRIVILEGES;

SHOW DATABASES;
Select user from mysql.user;
