apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: kube-prometheus-stack-prometheus
  namespace: kube-prometheus-stack
spec:
  serviceMonitorSelector:
    matchLabels:
      serviceMonitorSelector: controllers-cbci
