apiVersion: v1
kind: Secret
metadata:
  name: cm-secrets
  annotations:
    docs: "https://github.com/jenkinsci/configuration-as-code-plugin/blob/master/docs/features/secrets.adoc"
type: Opaque
data:
  secretAdvisorMail: {{ .Values.secrets.advisorMail | b64enc | quote }}
