apiVersion: v1
kind: Secret
metadata:
  name: oc-secrets
  annotations:
    docs: "https://github.com/jenkinsci/configuration-as-code-plugin/blob/master/docs/features/secrets.adoc"
type: Opaque
data:
  secretGithubToken: {{ .Values.secrets.github.token | b64enc | quote }}
  secretGithubUser: {{ .Values.secrets.github.user | b64enc | quote }}
  secretAdvisorMail: {{ .Values.secrets.advisorMail | b64enc | quote }}
