#Ref: https://docs.cloudbees.com/docs/cloudbees-cd/latest/install-k8s/k8s-platform-specific-configurations#_configuring_values_yaml_for_alb_support

##---------------------------------------------
## Plataform
##---------------------------------------------

platform: eks

##---------------------------------------------
## Ingress Controller
##---------------------------------------------

ingress:
  enabled: true
  host: ${hostname}
  class: alb
  annotations:
    alb.ingress.kubernetes.io/certificate-arn: ${cert_arn}
    alb.ingress.kubernetes.io/scheme: internet-facing
    # alb.ingress.kubernetes.io/backend-protocol: "HTTP"
    # alb.ingress.kubernetes.io/ip-address-type: "ipv4"
    # alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
    # alb.ingress.kubernetes.io/ssl-redirect: '443'
nginx-ingress:
  enabled: false
ingress-nginx:
  enabled: false

##---------------------------------------------
## Flow storage configuration section
##---------------------------------------------

storage:
  volumes:
    serverPlugins:
      name: flow-server-shared
      accessMode: ReadWriteMany
      storageClass: efs
    repositoryStorage:
      storage: 10Gi
      storageClass: efs
    doisStorage:
      storageClass: efs
    boundAgentStorage:
      storageClass: efs

#---------------------------------------------
# Volume configuration section
#---------------------------------------------
# Fixes mounting issues with the flow-server-init-job

# Fixes mounting issues with repository and devops insights
volumePermissions:
  enabled: false
# Fixes mounting issues with the flow-server-init-job
# No Longer needed because it is fixed by the global one one below
# server:
#   volumesPermissionsInitContainer:
#     enabled: false
