clusteredMode: false

##---------------------------------------------
## Flow storage configuration section
##---------------------------------------------

storage:
  volumes:
    serverPlugins:
      accessMode: ReadWriteOnce
      # Storage class for plugins directory. Currently it has to be shared across server and web replicas.
      # Server and web are co-located using hard affinity rule for non clusteredMode. StorageClass is null here to ensure the same behavior across all cloud providers
      # (it forces storage class to fall back to  "default" disk based ReadWriteOnce platform specific storage class)
      storageClass: efs
      storage: 5Gi

    repositoryStorage:
      storage: 10Gi

##---------------------------------------------
## Flow components/workloads configuration section
##---------------------------------------------
server:
  resources:
    limits:
      cpu: 3
    requests:
      cpu: 2
  nodeSelector:
    ci_type: cb-apps
  tolerations:
    - key: dedicated
      operator: Equal
      value: cb-apps
      effect: NoSchedule

jobInit:
  nodeSelector:
      ci_type: cb-apps
  tolerations:
    - key: dedicated
      operator: Equal
      value: cb-apps
      effect: NoSchedule

web:
  nodeSelector:
    ci_type: cb-apps
  tolerations:
    - key: dedicated
      operator: Equal
      value: cb-apps
      effect: NoSchedule

repository:
  nodeSelector:
    ci_type: cb-apps
  tolerations:
    - key: dedicated
      operator: Equal
      value: cb-apps
      effect: NoSchedule

dois:
  nodeSelector:
    ci_type: cb-apps
  tolerations:
    - key: dedicated
      operator: Equal
      value: cb-apps
      effect: NoSchedule

boundAgent:
  nodeSelector:
    ci_type: cb-apps
  tolerations:
    - key: dedicated
      operator: Equal
      value: cb-apps
      effect: NoSchedule


database:
  dbName: "flow"
  dbUser: "flow"
  dbPassword: "flow"
  dbType: "mysql"
  dbPort: 3306
  clusterEndpoint: "mysql.db"
  mysqlConnector:
    enabled: false

##---------------------------------------------
## Flow server admin credentials section
##---------------------------------------------

flowCredentials:
  ## Name of the secret containing the admin user password to use. If set, the admin user password
  ## will be read from the secret instead of the plain-text `adminPassword` (not recommended for production).
  ##
  ## The data field must contain base64 encoded value for key 'CBF_SERVER_ADMIN_PASSWORD'.
  ## E.g., kubectl create secret generic flow-admin-secret --from-literal=CBF_SERVER_ADMIN_PASSWORD='rrx!*d$z75Dsb'
  ##
  ## Uncomment the following line to set the name of the secret to use to read the admin user password.
  # existingSecret: flow-admin-secret
  ##
  ## IMPORTANT: This is clearly not meant for production use and is only meant for demo environments
  ## where security may not be a concern. Use of `existingSecret` is preferred.
  adminPassword: "admin"
