#https://docs.cloudbees.com/docs/cloudbees-cd/latest/install-k8s/k8s-platform-specific-configurations#_configuring_values_yaml_for_alb_support
ingress:
  enabled: true
  host: cd.crl.core.pscbdemos.com
  class: alb
  annotations:
      alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-east-1:324005994172:certificate/277a45f8-03b5-4150-a2de-45f1f642c647
platform: eks

nginx-ingress:
  enabled: false
