#https://artifacthub.io/packages/helm/external-dns/external-dns
#https://github.com/kubernetes-sigs/external-dns/tree/master/charts/external-dns/Chart.yaml
provider: "aws"
policy: "sync"
logLevel: "debug"
nodeSelector:
  kubernetes.io/os: linux
  kubernetes.io/arch: amd64
